import { Figtree } from "next/font/google";
import "./globals.css";
import Header from "./components/organism/Header";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtree.className} bg-secondary antialiased`}>
        <Header />
        <main className="grid justify-center gap-24 px-4 md:px-8 lg:px-12 xl:px-24">
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
