import { Astloch } from "next/font/google";

const astloch = Astloch({
  subsets: ["latin"],
  variable: "--font-astloch",
  display: "swap",
  weight: "700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProjectsPageLayout({ children }) {
  return (
    <main className={`${astloch.className} bg-green-900`}>{children}</main>
  );
}
